### ISSUE TITLE
cornerstone.imageCache.purgeCache() caused error

### ISSUE THREAD

**Issue by xpackal5** [cornerstonejs/cornerstone#93] opened 2017-02-26 07:50 UTC
Hello cornerstone.imageCache.purgeCache() caused this error. 

```
Uncaught TypeError: imagePromise.reject is not a function
    at Object.<anonymous> (cornerstone.js:699)
    at Object.<anonymous> (jquery.min.js:2)
    at i (jquery.min.js:2)
    at Object.add [as done] (jquery.min.js:2)
    at Array.<anonymous> (jquery.min.js:2)
    at Function.each (jquery.min.js:2)
    at Object.<anonymous> (jquery.min.js:2)
    at Function.Deferred (jquery.min.js:2)
    at Object.then (jquery.min.js:2)
    at decache (cornerstone.js:695)
```

**Comment by swederik** [comment] 2017-04-06 07:54
Hi there,

This should be fixed in the latest version of the CornerstoneWADOImageLoader. The relevant commit is here: https://github.com/chafey/cornerstoneWADOImageLoader/commit/5e3aaabb81e6c49c4835ea23bd8c671b9da5faf4

The problem is that we were returning a promise, which doesn't have the reject function.

**Comment by leonardorame** [comment] 2017-04-16 20:48
Hi, I'm started getting this error since `v0.14.3` from `2017-04-06`. It's somewhat difficult to reproduce, first I load a study containing images from WebLoader and WADOImageLoader, then I try to load another study (without refreshing the page) and the first thing I do is calling `cornerstone.imageCache.purgeCache();`, that's where I get the famous:

```
TypeError: cachedImage.imagePromise.reject is not a function
at removeImagePromise (http://127.0.0.1/displaystudy/js/cornerstone/cornerstone.js:1932:34)
at Object.purgeCache (http://127.0.0.1/displaystudy/js/cornerstone/cornerstone.js:1965:13)
```
Maybe its a bug or should I purge the cache using a different method?.

Leonardo.

**Comment by swederik** [comment] 2017-04-17 13:10
Hi Leonardo,

I think this is a bug with the Web Image Loader. It is still returning a promise, so it can't be rejected. We need to switch it to just return the Deferred:

https://github.com/chafey/cornerstoneWebImageLoader/blob/master/dist/cornerstoneWebImageLoader.js#L200

Thanks for the report!

**Comment by leonardorame** [comment] 2017-04-17 14:10
Great!, I'll be watching cornerstoneWebLoader for the fix.

**Comment by leonardorame** [comment] 2017-04-17 14:50
BTW, I tested it and I can confirm that fixes de issue.

**Comment by diego0020** [comment] 2017-04-17 17:43
Hi, please remember that according to the spec https://github.com/chafey/cornerstone/wiki/ImageLoader 
image loaders should return *promises*; not *deferred*. Returning *deferred* would also mean tighter coupling with jquery.

**Comment by leonardorame** [comment] 2017-06-24 02:59
Hi Erik, I still see `return deferred.promise()` instead of `return deferred;` in cornerstoneWebImageLoader.

Could you apply this quick fix?.

**Comment by swederik** [comment] 2017-06-24 11:22
Hi @leonardorame,

I actually thought I had changed that already. Sorry about that.

I've just released version cornerstoneWebImageLoader 0.8.2 with the fix applied: https://github.com/chafey/cornerstoneWebImageLoader/commit/94e5649fb18103a1ccb882a07800672df0df9db2

**Comment by leonardorame** [comment] 2017-06-24 12:25
Thank you very much Erik, I'm testing now.





On Saturday, June 24, 2017, 8:23:37 AM GMT-3, Erik Ziegler <notifications@github.com> wrote:


Hi @leonardorame,

I actually thought I had changed that already. Sorry about that.

I've just released version cornerstoneWebImageLoader 0.8.2 with the fix applied: chafey/cornerstoneWebImageLoader@94e5649

**Comment by dannyrb** [comment] 2017-06-24 13:11
I've been watching this issue as I was experiencing the same issue. I'd cache 4k images, and at 2k I'd receive the same error for each remaining image.

Pulling in the latest package, all images are pulled in and cached as expected :+1:

Tangentially related, the loader has been updated to return `deferred`. What impact does that have on?:

- #76 
- #43 

I think this change has all/most returning `deferred`? I'm not sure a formal decision was ever reached, but it may be worth considering updating the documentation regarding custom loader implementations and/or closing out those issues?

**Comment by diego0020** [comment] 2017-06-27 15:18
I have been thinking about this. Taking a step back, the image loader issues a promise, and then the cache waits for the promise to be fulfilled (or fail). Rejecting the promise would be something that the image loader would do to tell the cache that the operation failed. So, in other words, it is a message from the image loader to the cache. 

Here we are trying to do a communication in the other direction, this is, the cache telling the image loader that some image is not required anymore. Therefore rejecting the promise is not the right mechanism. 

For the moment I have thought of two ways to achieve this communication from cache to image loader. 
- returning a more complex object from the image loader that has a method to cancel the request.
- having a method in the loader for cancelling the request associated for a certain imageId

After receiving the message, the imageLoader would cancel the underlying request an do the required clean up; and then reject the promise. So, only the entity that issued the promise should reject it.

**Closed** 2017-12-12 08:00 UTC
Labels: bug
