### ISSUE TITLE
fitToWindow: null rowPixelSpacing

### ISSUE THREAD

**Issue by jssuttles** [cornerstonejs/cornerstone#316] opened 2018-10-10 00:52 UTC
![image](https://user-images.githubusercontent.com/8527741/46706907-20ae5980-cc05-11e8-8808-deb81fc2c855.png)
This causes a NaN scaleFactor.

**Comment by dannyrb** [comment] 2018-10-10 15:04
Hi @jssuttles, thanks for reporting an issue!

Moving forward, can you please include:

- The steps to reproduce the issue
    - Including any assets (ie. anonymized image)
- The version of cornerstone, the image loader, etc. that you are using
- The code as text, rather than as an image

Bonus points if the issue is accompanied with a minimal reproduction in `codepen.io` or `jsfiddle.net`

**Comment by jssuttles** [comment] 2018-10-10 18:49
Sorry. I can't anonymize the images. They have burned in PHI. I can tell you that they are ultrasounds and that they have multiple instances per series that have multiple frames.

cornerstone version: 2.2.5
custom image loader that allows direct file system file loading through electron based on cornerstone wado image loader: 2.1.4

I worked around it by setting the rowPixelSpacing and columnPixelSpacing on cornerstoneimageloaded to undefined if null.

**Comment by kofifus** [comment] 2018-10-16 23:35
This is a bug ..

in https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/src/imageLoader/wadouri/metaData/metaDataProvider.js#L43-L44

we set them to null

```
    let columnPixelSpacing = null;
    let rowPixelSpacing = null;

```

therefore in https://github.com/cornerstonejs/cornerstone/blob/master/src/internal/getDefaultViewport.js#L111-L112

it should be changed to:

```
      rowPixelSpacing: image.rowPixelSpacing === undefined || image.rowPixelSpacing === null ? 1 : image.rowPixelSpacing, // VOYAGER
      columnPixelSpacing: image.columnPixelSpacing === undefined || image.columnPixelSpacing === null ? 1 : image.columnPixelSpacing, // VOYAGER


```

**Comment by kofifus** [comment] 2018-10-17 22:56
I submitted PR https://github.com/cornerstonejs/cornerstone/pull/319

**Comment by dannyrb** [comment] 2019-03-24 12:23
@kofifus, it looks like we check for `undefined` in both of those places, and then use one as a fallback if we have no value, so checking for `null` should not be an issue.

I'll mark this as a verified bug and comment on the existing PR with feedback items so we can get this fix merged.

**Comment by dannyrb** [comment] 2019-03-24 12:44
Upon further review, the example definitely does not handle this case well. It's also unclear if this is the intended behavior of `core` for `null` pixelSpacing values. I've added some information to the PR to aid in discussion.

**Comment by kofifus** [comment] 2019-03-24 21:42
I think we should as well

Note matching PR https://github.com/cornerstonejs/cornerstoneTools/pull/647/files which was merged

**Closed** 2021-09-13 10:09 UTC
Labels: Work In Progress, 🐛 Bug: Report
